param(
    [string]$LavDirectory,
    [string]$FixtureDirectory,
    [string]$OutputDirectory,
    [switch]$CompileOnly
)
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
. (Join-Path $PSScriptRoot 'Enter-BuildEnvironment.ps1')
$out = Join-Path $root 'bluray/build/read-errors'
New-Item -ItemType Directory -Force -Path $out | Out-Null
Push-Location $out
try {
    & cl.exe /nologo /EHsc /std:c++17 /MT /W4 /O2 /DUNICODE /D_UNICODE /DNOMINMAX "/I$root/src/thirdparty/BaseClasses" "/I$root/src/thirdparty/minhook/minhook/include" "/I$root/src/thirdparty/LAVFilters/src/include" "/Fe:$out/lav-read-error-test.exe" "$root/bluray/probe/lav-read-error-test.cpp" /link /LTCG "$root/bin/lib/Release_x64/BaseClasses.lib" "$root/bin/lib/Release_x64/minhook.lib" ole32.lib oleaut32.lib strmiids.lib winmm.lib uuid.lib
    if ($LASTEXITCODE -ne 0) { throw 'Read-error probe compilation failed.' }
} finally { Pop-Location }

if (!$CompileOnly) {
    if (!$LavDirectory) { $LavDirectory = Join-Path $root 'src/thirdparty/LAVFilters/src/bin_x64' }
    if (!$FixtureDirectory) { throw 'Provide -FixtureDirectory generated by make-read-error-fixture.py.' }
    if (!$OutputDirectory) { $OutputDirectory = Join-Path $out ('run-' + (Get-Date -Format 'yyyyMMdd-HHmmss')) }
    & python (Join-Path $PSScriptRoot 'test-lav-read-errors.py') --probe (Join-Path $out 'lav-read-error-test.exe') --lav $LavDirectory --fixture $FixtureDirectory --output $OutputDirectory
    if ($LASTEXITCODE) { throw 'LAV read-error regression failed.' }
}
